name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Init SDK TinyUSB submodule
        run: |
          cd pico-sdk
          git submodule update --init

      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi cmake ninja-build

      - name: Configure
        run: cmake -S . -B build -G Ninja -DPICO_BOARD=pico2

      - name: Build
        run: cmake --build build

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: blink-uf2
          path: build/blink.uf2  

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: blink-uf2
          path: build/blink.uf2

